### ISSUE TITLE
결과 보고서 가져오기에서 프로젝트 이름 추가

### ISSUE THREAD

**Issue by KJG04** [DSM-TeaMit/Ace#111]
## 개요

> 제목을 바꿔야 해서 프로젝트 이름이 필요함
> projectName이라는 필드 이름으로 추가 바람

## 작업 내용

- [ ] 기능 구현

**Comment by pjp0704** [comment]
보고서의 제목이 프로젝트 이름을 적는 것인지, 해당 프로젝트의 주제 자체를 적는 것인지 이전에 이야기가 한 번 있었던 것으로 기억합니다. 둘 다 되는 것 같긴 하더라구요. 그래서 적는 사람 맘대로 하라고 보고서 제목을 subject라는 필드로 줬습니다.

즉 이슈에서 필요하다고 하신 projectName의 역할이 subject와 동일하다고 할 수 있겠습니다.

확인하시면 이모지 달아주시고, 질문 있으시면 남겨주시면 됩니다. 이모지 달아두시면 이슈 닫겠습니다

**Comment by KJG04** [comment]
> 보고서의 제목이 프로젝트 이름을 적는 것인지, 해당 프로젝트의 주제 자체를 적는 것인지 이전에 이야기가 한 번 있었던 것으로 기억합니다. 둘 다 되는 것 같긴 하더라구요. 그래서 적는 사람 맘대로 하라고 보고서 제목을 subject라는 필드로 줬습니다.
> 
> 즉 이슈에서 필요하다고 하신 projectName의 역할이 subject와 동일하다고 할 수 있겠습니다.
> 
> 확인하시면 이모지 달아주시고, 질문 있으시면 남겨주시면 됩니다. 이모지 달아두시면 이슈 닫겠습니다

그렇긴 한데
제가 하고싶은건 웹의 타이틀을 바꾸고 싶은거라서
예를 들면 프로젝트 'ABCD'의 결과 보고서를 보고 있으면 웹 타이틀을 'ABCD의 결과 보고서 - Teamit'로 해버리는 기능
그래서 프로젝트 이름이 필요합니다

**Comment by pjp0704** [comment]
이슈 #117 로 병합
