### ISSUE TITLE
유저 정보 가져오기에서 500 서버 오류

### ISSUE THREAD

**Issue by KJG04** [DSM-TeaMit/Ace#112]
## 개요

> 유저 정보 가져오기에서 오류 500 뜸
> 유저 uuid는 0ecfaf8f-62f5-4a13-ba01-76966aa98e13
> 근데 왠지 46번 이슈의 내용인거 같기도 하고
> 수정 바람

<img width="990" alt="스크린샷 2022-03-27 오후 9 55 24" src="https://user-images.githubusercontent.com/66928355/160282454-b0b4c691-0776-4e5a-bc6f-76c41e61069a.png">

## 작업 내용

- [ ] 오류 수정

**Comment by pjp0704** [comment]
uuid가 존재하지 않을 때의 예외 처리 부분이 누락되어 있어서 그런 듯 하네요.
근데 저 uuid는 어디서 나온 건가요

**Comment by KJG04** [comment]
> uuid가 존재하지 않을 때의 예외 처리 부분이 누락되어 있어서 그런 듯 하네요.
> 
> 근데 저 uuid는 어디서 나온 건가요
> 
> 

uuid는 유저 uuid이고
uuid 담아서 보냈는데 uuid가 없다는게 무슨 말이죠

**Comment by pjp0704** [comment]
해당 유저가 존재하지 않을 때의 404 처리가 안 되어 있다는 뜻입니다. 실제로 DB에 해당 UUID는 없는 걸로 확인됐어요
그래서 요청에 들어 있는 UUID는 임의로 입력하신 건지 여쭤본 것이었습니다

**Comment by KJG04** [comment]
> 해당 유저가 존재하지 않을 때의 404 처리가 안 되어 있다는 뜻입니다. 실제로 DB에 해당 UUID는 없는 걸로 확인됐어요 그래서 요청에 들어 있는 UUID는 임의로 입력하신 건지 여쭤본 것이었습니다

변수 잘못써서 프로젝트 uuid 가져다가 써버렸네요;
해결됐습니다
