### ISSUE TITLE
보고서를 생성했음에도 프로필의 보고서에서 응답에 보고서 목록이 비어있는 오류 

### ISSUE THREAD

**Issue by KJG04** [DSM-TeaMit/Ace#113]
## 개요

> uuid가 0ecfaf8f-62f5-4a13-ba01-76966aa98e13인 프로젝트의 계획서와 결과 보고서를 생성했음에도
> 마이 페이지에서 보고서 목록이 비어서 오는 오류 수정하기

## 작업 내용

- [ ] 오류 수정

**Comment by pjp0704** [comment]
해당 API에서는 현재 제출되어 있는 보고서 목록만 표시됩니다.
제출하지 않은 보고서도 목록에 표시되어야 하나요?
