### ISSUE TITLE
Raw query 사용 API에서 변경된 컬럼명이 제대로 반영되지 않은 문제

### ISSUE THREAD

**Issue by KJG04** [DSM-TeaMit/Ace#169]
## 개요

> 보고서 목록에서 프로젝트 이름이 누락된 응답이 오는 버그
> 154e64ff-b484-43d9-9faa-89836c4a18a7
> 보고서 목록에서는 결과 보고서가 있다고 뜨지만 들어가면 404가 뜸

## 작업 내용

- [ ] 버그 수정

**Comment by pjp0704** [comment]
추가 사항: 똑같이 Raw Query를 사용하는 검색 API에서도 동일 현상이 발생함에 따라 컬럼명 변경 후 변경된 컬럼명과 쿼리의 불일치로 인한 문제로 보임, 따라서 검색 API도 묶어서 해당 이슈에서 처리
